# Generated by Django 5.0.6 on 2024-05-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('toy_name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='toy_name')),
                ('toy_model', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='toy_model')),
                ('toy_price', models.FloatField(verbose_name='toy_price')),
                ('toy_description', models.CharField(max_length=2000, verbose_name='toy_description')),
            ],
        ),
    ]
