# Generated by Django 5.0.6 on 2024-05-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='toy_description',
            field=models.CharField(max_length=2000, verbose_name='Toy Description'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='toy_model',
            field=models.CharField(max_length=10, verbose_name='Toy Model'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='toy_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Toy Name'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='toy_price',
            field=models.FloatField(verbose_name='Toy Price'),
        ),
    ]
