# Generated by Django 5.0.6 on 2024-05-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_alter_toy_toy_description_alter_toy_toy_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='toy_price',
            field=models.CharField(max_length=10, verbose_name='Toy Price'),
        ),
    ]
